import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
<<<<<<< HEAD
import { Toaster } from "@/components/ui/toaster";
=======
import { Toaster } from "@/components/ui/sonner";
import { QueryProvider } from "@/providers/QueryProvider";
>>>>>>> 44fac76cb1a89256af69385d641ed87f3744a645
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
=======
  title: "Monte Carlo",
  description: "Travel Management Panel",
>>>>>>> 44fac76cb1a89256af69385d641ed87f3744a645
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        {children}
        <Toaster />
=======
        <QueryProvider>
          {children}
          <Toaster position="top-right" />
        </QueryProvider>
>>>>>>> 44fac76cb1a89256af69385d641ed87f3744a645
      </body>
    </html>
  );
}
